### ISSUE TITLE
Properties Window design

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#101]
In the "File" drop down we need to add a Properties option. 

The Properties window design should contain;
- form field for level name, this would be the first option (see how google docs do it)
- form fields for level size width and height with a warning if it goes over recommended iPhone 3g size 
- form field for character sprite size
- form field for tile sizes
- form field for level description
- tab for customize game screens (i.e. about / you win / you loose)
- tab for game physics
- tab for 

Tabs would probably be   General  |  Sounds  |  Game Screens  |  Physics  |  Sounds

**Comment by thornyd** [comment]
Initial design is done.
http://img838.imageshack.us/img838/6953/gamecreator53.jpg

**Comment by marsh0lion** [comment]
Should be able to specify game start properties:

health remaining on player
maximum health of player
timer start on level start yes/no
initial timer value

physics options
etc.

**Comment by marsh0lion** [comment]
Graphics don't fit what we are currently doing.

**Comment by instinct** [comment]
good call.

the new graphics are slick... dave should put them online for us or email them to you :)

**Comment by thornyd** [comment]
heres a screenshot
http://i41.tinypic.com/ajw41j.jpg

**Comment by marsh0lion** [comment]
Brett has implemented the new graphics
