### ISSUE TITLE
Object properties button 

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#122]
The button for changing default "object properties" needs to be re thought, re designed in photoshop since it is the only button left at the bottom of the screen. Some ideas are;

1) when you click on the item / tile / whatever it is then a drop down is displayed (similar to how facebook does images),simply one options would be "change default properties for this item / object"

-- before doing this look at how facebook actually does this --

2) another design to play with would be to only highlight the "properties" button IF a tile has been clicked. So it would always start grey.

**Comment by thornyd** [comment]
New design and UI approved, graphics sent to Brian.

**Comment by marsh0lion** [comment]
implemented
