### ISSUE TITLE
Logout design dropdown

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#123]
The level editor needs a better more elegant logout button. 

Simply copy what facebook does. There is a little arrow pointing down (in our case it'll be grey like in wordpress), that when clicked it will show the user a handful of options, logout being the only one we have right now...

As usual show Dan and team when done for feedback. Then fire image off to Brian :)

**Comment by thornyd** [comment]
Design approved and sent graphics to Brian.

**Comment by marsh0lion** [comment]
implemented
