### ISSUE TITLE
Tile and Items properties design tweaks

### ISSUE THREAD

**Issue by thornyd** [instinct/GameFroot#131]
Some tweaks to be implemented.

**Comment by thornyd** [comment]
Design approved and have sent graphics to Brian.

**Comment by marsh0lion** [comment]
Implemented

**Comment by marsh0lion** [comment]
closed wrong issue

**Comment by marsh0lion** [comment]
Thee are issues with the vertical tabs that we have talked about

**Comment by marsh0lion** [comment]
now implemented (it was a bit of a pain)
