### ISSUE TITLE
spinning .gif images for save game + preview game

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#156]
The user needs visual feedback for anything that takes time to happen. Lets start with Save Game and Preview Game. 

Use standard WordPress spinning graphic for white bg in Save window. And we'll talk more about the Preview Game loader.

**Comment by marsh0lion** [comment]
These need to be added to wherever there is a process that is taking a lot of time

**Comment by marsh0lion** [comment]
done on load level, Save level and preview
