### ISSUE TITLE
saving bug

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#158]
In a situation when you have slow internet. 

I entered the name of my level. Clicked save. Nothing happened. I clicked save again and again and again. Eventually it saved. 

I refreshed my page. Hit load level. And my game had been saved multiple times.

Rather the button should be disabled while its saving.

The same way when you add something to your watchlist in trademe.

**Comment by marsh0lion** [comment]
A spinner has been added (but the box doesn't looking to great)

**Comment by instinct** [comment]
Show me this tomorrow so we can decide whether Dave needs to design anything :)
