### ISSUE TITLE
when opening saved levels

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#159]
No background image is weird. It should always show an image.

The main problem though is that the Open Button didnt seem to open my level. Might be because my internet is slow - but in which case this show the need for  a loading graphic.

**Comment by marsh0lion** [comment]
This is because the user has not saved a background - need th check there is either a default on save or when creating a new level

**Comment by marsh0lion** [comment]
Default is set when you save the level, and is also set when retrieving list of levels, some existing levels may have no background when played
