### ISSUE TITLE
New features to add to the robot editor

### ISSUE THREAD

**Issue by vlad86** [instinct/GameFroot#170]
Here is a list of some more missing functions and features which could be very useful in the robot editor!
They mainly concern item parity!
1) Add / change time
2) Add / change ammo - I think this is already in!
3) Add / change life
4) Turn item / robot into save point
5) add / remove jetpack fuel - I think this has also been discussed!

**Comment by InstinctBrett** [comment]
1. Time is done.
2. Change ammo should be done via inventory
3. I think that lives were the only thing not implemented, but we could do that with inventory.
4. Added 'trigger checkpoint' to Events tab.
5. Jetpack and fuel should be granted via inventory.
