### ISSUE TITLE
navigator cursors

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#173]
1) when dragging the blue area around (i.e. mouse down) the cursor needs to be the closed hand
2) when rolling over the arrow to close the navigator it needs to turn into a hand to indicate that it can be clicked on

**Comment by marsh0lion** [comment]
I'll need some graphics to complete this - Dave could you please provide and assign this back to me when you've e-mailed them through.

Cheers

**Comment by instinct** [comment]
Nope. Lets just use the pointer cursor, and then when in the blue area, lets use the move cursor... that should be explanatory enough for users.

**Comment by marsh0lion** [comment]
In that case, it's done
