### ISSUE TITLE
Login button / gravatar image - add more details

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#178]
When you click on this and the window show I'd like to show more then just the Logout link. Can we add the following:

<b>Your Account</b>
dan@instinct.co.nz
Logout

That way when we are testing we can see what email addresses we're using when we're logged in and testing.

**Comment by marsh0lion** [comment]
what would you like "_Your Account_" go to?

**Comment by instinct** [comment]
Nowhere. That bit is just a heading for now :)

**Comment by marsh0lion** [comment]
ok, done
