### ISSUE TITLE
API Calls for Brett

### ISSUE THREAD

**Issue by marsh0lion** [instinct/GameFroot#219]
The following calls are needed for Robot editor:
# done
- get list of robots on current Level [done]
- get list of levels owned by the user [done]
- save new robot script [done]
- save existing robot script [done]
- get list of music available from this level
# in progress
# todo

**Comment by marsh0lion** [comment]
get list of levels owned by the user - use the get_user_levels API call

**Comment by marsh0lion** [comment]
save new robot script/save existing script - use the save_script API call

**Comment by marsh0lion** [comment]
get List of robots on the current level use the robots.getLevelRobots() function call. This returns a list of id's that can be feed to load script to get the actual script (Let me know if you'd like this padded out a little).

**Comment by InstinctBrett** [comment]
To give the robot editor something to preload into its panel, load the robot editor with this URL:
`/roboteditor/?initialScript=`
and use something like JavaScript's encodeURIComponent() function to encode a complete Robot JSON object.

If you wish me to load an existing robot in the database, load this URL:

``` /roboteditor/?robotID=1234```
I will `parseInt(robotID,10)` it for security.
```

**Comment by InstinctBrett** [comment]
If as part of the above you pass an `item_id=abcd` (string or number) I will pass it back to whatever 'updatedRobot' JS callback the level editor provides.

**Comment by InstinctBrett** [comment]
@marsh0lion Some of these API commands might need _NOT_LOGGED_IN_ as a response - if the robot editor tries to request levels owned by a user not logged in.

**Comment by marsh0lion** [comment]
To get the list of available music use bgMusic.getAvailableBackgroundMusic()

**Comment by InstinctBrett** [comment]
Moving on hold API calls to new ticket. closing this one.
