### ISSUE TITLE
Tabs slow to load content

### ISSUE THREAD

**Issue by thornyd** [instinct/GameFroot#224]
Frequently content is very slow to load in terrain, items, and characters tabs. Sometimes it just displays a blank tab. Here's a screenshot: http://i40.tinypic.com/qryvyw.png

**Comment by instinct** [comment]
Any more information on this?

**Comment by marsh0lion** [comment]
Chrome (and possibly other browsers) won't load an image until it comes on screen. If you can click where the image should be and place it on the tile map, and it appears there, then the functionality is fine.

It's still something that we'll need to look into though.

**Comment by marsh0lion** [comment]
These should be a lot quicker now
