### ISSUE TITLE
Tile behaviour missing field

### ISSUE THREAD

**Issue by jmgomezg** [instinct/GameFroot#238]
Some tiles (terrains) are missing the behaviour field, here check the tile num 1605 for example on this level:

http://staging.doublehappy.co.nz/?gamemakers_api=1&type=json&map_id=2689

**Comment by marsh0lion** [comment]
These were descturctable and ice tiles that have now been fixed on live

**Comment by jmgomezg** [comment]
This is still an issue since some old levels like "Iceberg Climbing" has a lot of missing tile behaviour, making the enemy AI get confused. I reckon we should clear up old levels.
