### ISSUE TITLE
Ghost issue

### ISSUE THREAD

**Issue by jmgomezg** [instinct/GameFroot#240]
Not too sure if this is an issue, but we didn't have it before, the ghost sprite is displaying a black area (prob cos the size of the png uploaded  was smaller than tile size?), see spritesheet:

http://staging.doublehappy.co.nz/?gamemakers_api=1&type=get_game_animations&id=2946

On that level in particular, the ghost was a robot, but the robot script is missing:
http://staging.doublehappy.co.nz/?gamemakers_api=1&type=json&map_id=2946

**Comment by marsh0lion** [comment]
That's correct. It appeared because previously transparent was set to black (it's now a slightly off black)
