### ISSUE TITLE
Robot property "immortal" conflicts with story point parameter "permanent"

### ISSUE THREAD

**Issue by jmgomezg** [instinct/GameFroot#264]
If we have a robot set as immortal means we can not destroy it, so if we also have a parameter "permanent" set to false on a story point robot, the robot will not be destroyed. I can check on my side and see if we have a "permanent" so we override the "immortal", but wondering if there is a better way. Any suggestions?

**Comment by InstinctBrett** [comment]
I think if a robot chooses to die, that's always alright and should
override the immortal flag.

 I guess Immortal refers to whether damage is taken,

or maybe if when the remaining health is zero or less if it will
trigger the out of health event, or if that event is not present, an
auto-death.

#ProRoboEuthanasia ;)

On 6/02/2012, at 11:50 AM, jmgomezg
reply@reply.github.com
wrote:

**Comment by jmgomezg** [comment]
Oh yeah, that's it, we apply immortal only when damage is taken and health is zero, makes totally sense!

**Comment by marsh0lion** [comment]
Jose - If you're happy with this, please close it

**Comment by jmgomezg** [comment]
Sure, closing!!
