### ISSUE TITLE
add blank tiles to the bottom and right when level size changes

### ISSUE THREAD

**Issue by nunomorgadinho** [instinct/GameFroot#276]
The level size (not screen size as you have appeared to have interpreted it as) represents the width and height (in tiles) of the entire level. Dan: when this is changed, do you want to truncate or add blank tiles to the bottom (in changing the height) and right (in changing the width) in the map editor or some other behaviour?

**Comment by marsh0lion** [comment]
I've completed this - don't try and set the level size to be hugely different or large size (due to a possible explosion in div's
