### ISSUE TITLE
layerX & layerY are used extensively in the character creator

### ISSUE THREAD

**Issue by marsh0lion** [instinct/GameFroot#288]
layerX & layerY do not work in IE (and are being phased out in Chrome) - use the following code instead (and offsetX & offsetY don't work in firefox):

path = new Object();
path.x = parseInt(event.originalEvent.offsetX / 48);
path.y = parseInt(event.originalEvent.offsetY / 48);

if (isNaN(path.x) || isNaN(path.y)) {
    // handle some firefox weridness
    path.x = parseInt(event.originalEvent.layerX / 48);
    path.y = parseInt(event.originalEvent.layerY / 48);
}

**Comment by InstinctBrett** [comment]
Fixed by updating character creator to jQuery 1.7.1
