### ISSUE TITLE
robot command 'flash screen' color property ignored

### ISSUE THREAD

**Issue by thornyd** [instinct/GameFroot#289]
Flash screen colour ignores chosen colour and flashes black.

**Comment by InstinctBrett** [comment]
retitling "robot command 'flash screen' color property ignored" and tagging game engine.
assigning vlad

**Comment by jmgomezg** [comment]
if it helps, the color property is missing on the robot script when returned to us, that why always flashes to black.

**Comment by vlad86** [comment]
Re-assigning to brett and robot editor as the robot doesn't actually provide a color!

**Comment by InstinctBrett** [comment]
fixed in svn 127
