### ISSUE TITLE
New User Experience

### ISSUE THREAD

**Issue by thornyd** [instinct/GameFroot#293]
here's the pic:
http://i42.tinypic.com/fz3tw5.jpg

**Comment by InstinctBrett** [comment]
This is not a helpful issue. closing so you'll hopefully re-write it into a more helpful 'what the problem is and what needs to be done'.

**Comment by thornyd** [comment]
Hey Brett, Dan told me to write that - I know as much about it as you
do. Probably best to ask him.

On 2 March 2012 14:47, Brett Taylor
reply@reply.github.com
wrote:
