### ISSUE TITLE
switch + moving tiles bug 1

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#3]
Bug with switches and moving tiles

1) put down a switch
2) click the green button on the switch as though you are about to select a moving tile
3) DO NOT SELECT A TILE, rather click done instead
4) now click the moving tile tool
5) then click on the tile you want to make a moving tile
6) BUG is now a line will draw from the moving tile to the switch

We think this is happening because the switch tool still thinks that it is still placing the first node of a moving tile. It needs to realize that it isnt.

**Comment by marsh0lion** [comment]
Fixed in subversion, yet to go to staging

**Comment by instinct** [comment]
Nice job!
