### ISSUE TITLE
publish_date is not updated when I edit and save a level

### ISSUE THREAD

**Issue by jmgomezg** [instinct/GameFroot#300]
Before the publish_date was updated every time I was doing some changes, now it doesn't seem to refresh, this is affecting the cached levels on the iPhone version as I use this date to detect if there has been any changes, otherwise I run from local files.

**Comment by marsh0lion** [comment]
I can't seem to replicate the issue on both staging and my dev environments. It is using the wordpress post_modified date.

**Comment by jmgomezg** [comment]
Seems working fine!
