### ISSUE TITLE
simple behaviour tabs are disabled when switching back from robot mode

### ISSUE THREAD

**Issue by InstinctBrett** [instinct/GameFroot#326]
1. Add a robot script to an item.
2. Switch back to simple behaviours, - navigate around the behaviour tabs, but make no field changes
3. Save and close the panel
4. Open the behaviour panel again
5. Switch back to simple behaviours (should this happen?)
6. Simple behaviour tabs won't be working... :(

**Comment by marsh0lion** [comment]
Fixed - Robot wasn't being deleted when switching back to simple properties
