### ISSUE TITLE
Character placement on tiles

### ISSUE THREAD

**Issue by thornyd** [instinct/GameFroot#333]
At the moment we can't place characters on tiles, but we really need to be able to.

**Comment by vlad86** [comment]
This is an engine issue re-assign to Brian

**Comment by marsh0lion** [comment]
We need to define how this is going to work. Placing characters on background and cloud tiles should be fine. Placing on solid and spike shouldn't be. Same with items.

**Comment by instinct** [comment]
Brett said if its placed on background it should be background no matter what.

I guess the idea being that you should be able to walk in front of spikes. Therefore it shouldn't be an issue.

Curious to hear Brett's thoughts :)

**Comment by marsh0lion** [comment]
Players can now be placed on background and cloud tiles, but not on solid or spike tiles (instant-death anyone)
