### ISSUE TITLE
Warning in editor - when opening a level if you already have a level open

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#336]
Abi accidentally just lost a whole lot of work. Abi did the following;

1) was working on a level
2) clicked file
3) clicked load level
4) loaded a different level
5) the level loaded as expected

But then Abi realised that she'd lost all her mornings work.

What we need to do is add a javascript warning at the 4th step. 

If you are in a level. Then go to open a new level it needs to say something along the lines of "are you sure you want to leave this page - all your changes will be lost if you don't save first".

**Comment by marsh0lion** [comment]
Confirmation box has been added
