### ISSUE TITLE
switch + moving tiles bug 2 

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#4]
Bug Two

1) put down a game object (wooden box will do)
2) put down a switch
3) click the green button on the switch as though you are about to select a moving tile
4) now click the pen / draw tool 
5) now select a game object or a terrain object or even a switch 
6) move the cursor back into the stage
7) “BUG” now whatever it is you have chosen will paint on the screen over and over until you click the “done” button to turn off the switch association alert window

= Switch Numbers =
The numbers on the buttons are not subtracting 

= Switches & Animated Tiles =
Switches do not effect moving “ animated ” tiles. Such as the saw blade - animated tiles like the saw blade that just always moves regardless of the switch.

Once you associated a switch with a moving tile, if you’ve got the switch brush still on, then it should go back to that (as last active brush / tool)

**Comment by marsh0lion** [comment]
Fixed in subversion, not yet on staging

**Comment by instinct** [comment]
Nice work. I'm closing this topic.
