### ISSUE TITLE
new higher resolution backgrounds

### ISSUE THREAD

**Issue by InstinctBrett** [instinct/GameFroot#48]
need new 768x512 backgrounds to replace all lower resolution backgrounds

**Comment by thornyd** [comment]
sent ya test version of jap bg, plz test and then I'll do the rest

**Comment by thornyd** [comment]
http://img268.imageshack.us/img268/6453/jungle2x.jpg
http://img217.imageshack.us/img217/9955/snowy2.jpg
http://img225.imageshack.us/img225/1668/western2.jpg
http://img840.imageshack.us/img840/723/japanese2.jpg
http://img703.imageshack.us/img703/3328/cyberpunk2.jpg
http://img695.imageshack.us/img695/9916/desert2.jpg
http://img52.imageshack.us/img52/2561/dungeonh.jpg

**Comment by vlad86** [comment]
Need the rest of the backgrounds, current ones are in and if a background is selected which doesn't exist in high res it is reset to the jungle background

**Comment by thornyd** [comment]
Sent ya the rest.

**Comment by thornyd** [comment]
Sent ya the new ones

**Comment by vlad86** [comment]
Sweet.. all sent backgrounds implemented
