### ISSUE TITLE
share game / embed window (brian & vlad)

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#57]
All we need to do here is display the person clicking the "share link" an embed code that they can use to embed the game on their own site. 

This is no different to how youtube does things.

this issue is dependent on issue #75

**Comment by marsh0lion** [comment]
Embed code created and displayed, I think the URL will need to wait until the site is brought back up properly

**Comment by marsh0lion** [comment]
embed updated - the page that the URL goes to is working fine
