### ISSUE TITLE
metrics using playtomic.com

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#63]
I think we need to integrate with an existing tool for capturing in game metrics. It looks like playtomic could be a useful tool for us to use.

**Comment by instinct** [comment]
Talked to Zynga about their metrics. They capture things like
1) most used characters
2) most used items/objects
3) most played levels
4) most played games

As corporate users will eventually be using GameFroot it is important that we capture this stuff on a per user account too. So lets assume;

Coke is our client and we draw them a coke can game object that gives the player 5 health points. We need to log how many times that has been collected in total so coke can see if it was worth the investment. Coke will want to see how many levels have been made that use the can. And they will want to see how many coke levels there are in general. A total count of how many levels exist.

**Comment by InstinctBrett** [comment]
nope. chuck testa.
