### ISSUE TITLE
share game / embed graphics

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#75]
Dave to design a box that drops down underneath the button on the upper right of the screen underneath the share button. Inspiration from here:

Link icon should be that instead of share this in my opinion.

http://maps.google.co.nz/

issue #57 is dependent on this issue.

**Comment by thornyd** [comment]
http://oi56.tinypic.com/nc1mx2.jpg

sent the stuffs to Brian

**Comment by marsh0lion** [comment]
images added
