### ISSUE TITLE
8bit styled BG image for BGs

### ISSUE THREAD

**Issue by instinct** [instinct/GameFroot#85]
Draw a new 8bit "future tech" styled background that people will be able to choose from. Thinking something along the lines of that game we saw on that 8bit game website. Just so we can say we can do it.

http://8bitflashgames.com/

**Comment by thornyd** [comment]
Here's what we got so far:
http://imageshack.us/photo/my-images/703/8bitidea.gif/

**Comment by thornyd** [comment]
Check it out 

http://oi54.tinypic.com/309o41u.jpg
