### ISSUE TITLE
repo: separate 'branches' and trunk into 'trunk' 

### ISSUE THREAD

**Issue by InstinctBrett** [instinct/GameFroot#99]
rearrange repository to have branches and trunk folders

old:
`/branches/...`
`/tags/...`
`/*`

new: 
`/branches/...`
`/tags/...`
`/trunk/*`

!!!THIS WILL LIKELY BREAK EVERYONES WORKING CHECKOUTS!!!
they will likely need to:
- (if changes are not checked in) make a patch of their changes
- delete their working checkouts
- `svn co` the new trunk folder into their working folders: `svn co http://.../trunk .` <-- trailing period!!!
- DO NOT run the ant script after this - there is no need.

**Comment by nunomorgadinho** [comment]
This will likely get everyone against me as well :-)

**Comment by instinct** [comment]
Don't start this until we've completed Milestone 1 :)

**Comment by marsh0lion** [comment]
Done
